package org.example.domain;

import org.example.interfaces.Reportable;

public class Admin extends User implements Reportable {
    public Admin(String name) {
        super(name);
    }

    @Override
    public int getBorrowLimit() {
        return 0;
    }

    @Override
    public void generateReport() {
        System.out.println("--- Library Report ---");
        System.out.println("Report generated by admin: " + getName());
    }
}